.\" Line Editor manpage
.\" (feel free to improve it if you have some time)
.TH lineedit 1 "2019-07-25" "1.2" "Line Editor Manual"
.SH NAME
lineedit \- edit text files, one line at the time
.SH SYNOPSIS
.B lineedit
.IR [filename]
.IR [-l|--list]
.SH DESCRIPTION
.B Lineedit
is a simple terminal-based text editor (using the `curses' library) which is
designed to edit one line at the time. When the program is run, the specified
file is read and listed (you can create new files by supplying a new filename).
The user can then enter a command.
.PP
If you're creating a
new file, start by appending new lines (the
.IR a
command). List of commands can be retrieved at any moment by typing a question mark.
.PP
When using line-specific commands, the user will usually be prompted to enter a line
number first. Make sure to enter only numbers (without dots, commas, spaces, etc.)
otherwise the command will fail. When you're done with editing, you can save the file
and quit the editor with the
.IR x
command.
.PP
If you're in the middle of editing and suddenly want to save the text to another file,
use the
.IR r
command and supply a new filename.
.PP
If the
.B -l
or
.B --list
parameter is supplied, the line editor will just print all text in the file with
line numbers at the left (similar to the internal
.IR
l
command) and quit.
.SH BUGS
The find command will sometimes fail. There is currently no known workaround.
