# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Volumes/Cougar/Users/redcreator37/Software Development/C++/Line-Editor"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Volumes/Cougar/Users/redcreator37/Software Development/C++/Line-Editor"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Volumes/Cougar/Users/redcreator37/Software Development/C++/Line-Editor/CMakeFiles" "/Volumes/Cougar/Users/redcreator37/Software Development/C++/Line-Editor//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Volumes/Cougar/Users/redcreator37/Software Development/C++/Line-Editor/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lineedit

# Build rule for target.
lineedit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lineedit
.PHONY : lineedit

# fast build rule for target.
lineedit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/build
.PHONY : lineedit/fast

src/display.o: src/display.cpp.o
.PHONY : src/display.o

# target to build an object file
src/display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/src/display.cpp.o
.PHONY : src/display.cpp.o

src/display.i: src/display.cpp.i
.PHONY : src/display.i

# target to preprocess a source file
src/display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/src/display.cpp.i
.PHONY : src/display.cpp.i

src/display.s: src/display.cpp.s
.PHONY : src/display.s

# target to generate assembly for a file
src/display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/src/display.cpp.s
.PHONY : src/display.cpp.s

src/editing.o: src/editing.cpp.o
.PHONY : src/editing.o

# target to build an object file
src/editing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/src/editing.cpp.o
.PHONY : src/editing.cpp.o

src/editing.i: src/editing.cpp.i
.PHONY : src/editing.i

# target to preprocess a source file
src/editing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/src/editing.cpp.i
.PHONY : src/editing.cpp.i

src/editing.s: src/editing.cpp.s
.PHONY : src/editing.s

# target to generate assembly for a file
src/editing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/src/editing.cpp.s
.PHONY : src/editing.cpp.s

src/lineedit.o: src/lineedit.cpp.o
.PHONY : src/lineedit.o

# target to build an object file
src/lineedit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/src/lineedit.cpp.o
.PHONY : src/lineedit.cpp.o

src/lineedit.i: src/lineedit.cpp.i
.PHONY : src/lineedit.i

# target to preprocess a source file
src/lineedit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/src/lineedit.cpp.i
.PHONY : src/lineedit.cpp.i

src/lineedit.s: src/lineedit.cpp.s
.PHONY : src/lineedit.s

# target to generate assembly for a file
src/lineedit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lineedit.dir/build.make CMakeFiles/lineedit.dir/src/lineedit.cpp.s
.PHONY : src/lineedit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lineedit"
	@echo "... src/display.o"
	@echo "... src/display.i"
	@echo "... src/display.s"
	@echo "... src/editing.o"
	@echo "... src/editing.i"
	@echo "... src/editing.s"
	@echo "... src/lineedit.o"
	@echo "... src/lineedit.i"
	@echo "... src/lineedit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

